---

- name: install packages
  apt:
    name: "{{ awscli_packages[awscli_python_version] }}"
    update_cache: true
    install_recommends: no
    cache_valid_time: 86400

- name: install pip packages
  pip:
    name: "{{ awscli_pip_packages + awscli_custom_pip_packages }}"
    executable: "{{ awscli_pip_binary[awscli_python_version] }}"
  when: not ansible_check_mode

- name: prepare configuration files
  block:
    - name: create dir /root/.aws
      file:
        dest: /root/.aws
        state: directory
        mode: 0700
    - name: create awscli config
      template:
        src: config.j2
        dest: /root/.aws/config
        mode: 0600
    - name: create awscli credentials
      template:
        src: credentials.j2
        dest: /root/.aws/credentials
        mode: 0600
      no_log: True
  when: awscli_skip_config is not defined and not ansible_check_mode
